| epoch   1 |    10/   90 batches | lr 0.001000 | 191.36 ms | loss 0.16710
| epoch   1 |    20/   90 batches | lr 0.001000 | 146.06 ms | loss 0.18279
| epoch   1 |    30/   90 batches | lr 0.001000 | 153.18 ms | loss 0.11860
| epoch   1 |    40/   90 batches | lr 0.001000 | 186.61 ms | loss 0.13262
| epoch   1 |    50/   90 batches | lr 0.001000 | 180.43 ms | loss 0.10167
| epoch   1 |    60/   90 batches | lr 0.001000 | 177.67 ms | loss 0.07876
| epoch   1 |    70/   90 batches | lr 0.001000 | 181.38 ms | loss 0.10072
| epoch   1 |    80/   90 batches | lr 0.001000 | 172.14 ms | loss 0.08693
| epoch   1 |    90/   90 batches | lr 0.001000 | 189.24 ms | loss 0.11087
data_source.shape:  torch.Size([5777, 2, 25, 36])
---------------------------------
data_source shape: torch.Size([5779, 2, 25, 36])
---------------------------------
data_source shape: torch.Size([5779, 2, 25, 36])
output shape: torch.Size([25, 1, 36])
output[[0]].shape: torch.Size([1, 1, 36])
output[:-1].shape: torch.Size([24, 1, 36])
truth shape: torch.Size([5803, 36])
test_result shape: torch.Size([5803, 36])
output truth shape: (5803, 36)
output test_result shape: (5803, 36)
test_result[0].shape, type (36,) float64
test_result.shape, type (5803, 36) float64
loss shape:  (5803, 36)
output_df shape: (5803, 108)
Traceback (most recent call last):
  File "train.py", line 150, in <module>
    main(args)
  File "train.py", line 115, in main
    val_loss = plot_and_loss(model, val_data, epoch, criterion, input_window, scaler, args.dim, labels)
  File "D:\PythonProject\Time_series_anomaly_detection\utils\plot_and_loss.py", line 128, in plot_and_loss
    output_df.to_csv("res/truth_test_loss_" + model_type + ".csv", index=False)
  File "D:\miniconda\envs\pytorch\lib\site-packages\pandas\core\generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "D:\miniconda\envs\pytorch\lib\site-packages\pandas\io\formats\format.py", line 1105, in to_csv
    csv_formatter.save()
  File "D:\miniconda\envs\pytorch\lib\site-packages\pandas\io\formats\csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "D:\miniconda\envs\pytorch\lib\site-packages\pandas\io\common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'res/truth_test_loss_Transformer.csv'