data_source shape: torch.Size([381, 2, 20, 36])
output shape: torch.Size([20, 1, 36])
output[[0]].shape: torch.Size([1, 1, 36])
output[:-1].shape: torch.Size([19, 1, 36])
truth shape: torch.Size([400, 36])
test_result shape: torch.Size([400, 36])
output truth shape: (400, 36)
output test_result shape: (400, 36)
test_result[0].shape, type (36,) float64
test_result.shape, type (400, 36) float64
loss shape:  (400, 36)
output_df shape: (400, 108)
---------------------------------
start SVM
---------------------------------
D:\miniconda\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
30 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.
Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "D:\miniconda\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\miniconda\envs\pytorch\lib\site-packages\sklearn\svm\_base.py", line 199, in fit
    y = self._validate_targets(y)
  File "D:\miniconda\envs\pytorch\lib\site-packages\sklearn\svm\_base.py", line 722, in _validate_targets
    % len(cls)
ValueError: The number of classes has to be greater than one; got 1 class
  warnings.warn(some_fits_failed_message, FitFailedWarning)
D:\miniconda\envs\pytorch\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan]
  category=UserWarning,
Traceback (most recent call last):
  File "train.py", line 150, in <module>
    main(args)
  File "train.py", line 115, in main
    val_loss = plot_and_loss(model, val_data, epoch, criterion, input_window, scaler, args.dim, labels)
  File "D:\PythonProject\Time_series_anomaly_detection\utils\plot_and_loss.py", line 133, in plot_and_loss
    clf = svm_c(loss_value, labels)
  File "D:\PythonProject\Time_series_anomaly_detection\utils\plot_and_loss.py", line 193, in svm_c
    clf = grid.fit(x_train, y_train)
  File "D:\miniconda\envs\pytorch\lib\site-packages\sklearn\model_selection\_search.py", line 926, in fit
    self.best_estimator_.fit(X, y, **fit_params)
  File "D:\miniconda\envs\pytorch\lib\site-packages\sklearn\svm\_base.py", line 199, in fit
    y = self._validate_targets(y)
  File "D:\miniconda\envs\pytorch\lib\site-packages\sklearn\svm\_base.py", line 722, in _validate_targets
    % len(cls)
ValueError: The number of classes has to be greater than one; got 1 class